import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Button, DatePicker } from 'antd'

import {useThemeContext} from '../src/context/themeContext'
import {UserContext} from '../src/context/userContext'

import { useTranslation } from 'react-i18next'


import moment from 'moment';
import 'moment/locale/ru';

import MainLayout from '../src/components/layouts/mainLayout'

export default function Home() {

  const theme = useThemeContext();

  // const currentUser = useContext(UserContext);

  const {t} = useTranslation();

  const branches = theme.branches.map(item => {
    return (
      <div> {item.name}</div>
    )
  });

  return (

    <div className={styles.container}>
      <Head>
        <title>Logos Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         <p> Welcome to LogosNext!</p>
        </h1>

      <Button type="primary">-------------antd button-------------------</Button>

      <DatePicker/>

      <p>{t('links.editPhoto')}</p>

      {branches}

       </main>
    </div>

  )
}
